### PR TITLE
fix: rewrite ring buffer to solve playback problems

### LINKED ISSUE #420: fix w_openal init and playback problems
There are numerous problems with `w_openal`, including little mistakes such as forgetting a not operator in error conditions, and also bigger problems such as ring buffer not working correctly as several consecutive `w_openal::update` calls do not play after likely 4 seconds.

having ring buffer embedded into `w_openal` class makes it much harder to maintain, thus better to segregate these two functionalities.

not using a buffer queue (overwrite on writes, read in partial) led to noises in audio playback, thus it's better to keep it and make playback contiguous.

### PR DESCRIPTION
**Pull request by cthulhu-irl**
# Pull Request Checklist

Please check if your pull request fulfills the following requirements:

  * [x] The commit message follows our guidelines
  * [ ] Tests for the changes have been added / updated (for feat / fix / refactor)
  * [x] Docs for the changes have been added / updated (for feat / fix / refactor)

## Pull Request Type

What kind of change does this pull request introduce?

  * [ ] Build: Changes that affect the build system or external dependencies
  * [ ] CD: Changes to our CD configuration files and scripts
  * [ ] CI: Changes to our CI configuration files and scripts
  * [ ] Docs: Documentation only changes
  * [ ] Feat: A new feature
  * [x] Fix: A bug fix
  * [ ] Perf: A code change that improves performance
  * [ ] Refactor: A code change that neither fixes a bug nor adds a feature
  * [ ] Test: Adding missing tests or correcting existing tests

## What is the current behavior?

Issue #420

## What is the new behavior?

Changes:
 - w_openal::update was not working after internal buffer was filled.
 - ring buffer code was removed and written separately in its own class encapsulation. including update and callback functions.
 - little mistakes in different areas were fixed to make this code working.

## Does this Pull Request introduce a breaking change?

  * [ ] Yes
  * [x] No

## Other information

Closes #420

### CODE REVIEW

File: wolf/media/w_openal.hpp [hunk 1]
```diff
@@ -14,8 +14,156 @@
...
+namespace internal {
+
+/**
+ * @brief spsc fixed-size continuous ring buffer. read/write in chunks.
+ *
+ * @tparam T an integral type. buffer read/write happens with memcopy.
+ */
+template <typename T>
+    requires std::is_integral_v<T>
+class w_ring_buffer {
```
Comment (PooyaEimandar) [inline wolf/media/w_openal.hpp:31]: Please move w_ring_buffer.hpp as a stand-alone header within "wolf::system" namespace and then include it here.

**Review by PooyaEimandar — CHANGES_REQUESTED** [review]

File: wolf/media/w_openal.hpp (hunk 1 above)
Comment (cthulhu-irl) [reply wolf/media/w_openal.hpp]: done. with a slight change of name from `w_ring_buffer` to `w_spsc_ring_buffer` to differentiate from normal (usually mpmc) ring buffer as it's now a general utility (and not internal) in the library.

**Review by PooyaEimandar — APPROVED** [review]
Thank you.
